bot_token: ""
guild_id: ""

role_update_period: 30 # In Seconds
code_expiry_time: 60 # In Seconds

database:
  type: "MONGODB"

  # MongoDB Configuration
  mongo:
    connection_string: ""
    database: ""

ranks:
  # Format (See below)
  # Permission: Role ID
  "group.donator": ""

messages:
  minecraft:
    # Default message when the player executes `/discord`
    default:
      - "&6&m------------------------------"
      - "&e&lDiscord: &flink"
      - "&7&o(( Click the above link to join our discord! ))"
      - "&6&m------------------------------"

    # When the player executes `/discord link` even though the player is already linked
    already_linked:
      - "&e&lDISCORD &8» &cYou are already linked!"

    # When the player executes `/discord unlink` even though the player is not linked
    not_linked:
      - "&e&lDISCORD &8» &cYou need to be already linked to do that!"

    # When the player executes `/discord link` and is not already linked
    link:
      - " "
      - "                           &e&lDISCORD LINKING"
      - "        &fHead over to our Discord server &7(( /discord ))"
      - "  &fand type &6/link %code% &fto get linked with your Discord"
      - "                   &faccount! The code expires in 1 minute!"
      - " "

    # When the player executes `/discord unlink` and is currently linked
    unlink:
      - "&e&lDISCORD &8» &cYou successfully unlinked with your discord account."

    # When the player executes `/discord whois <target>` and target is linked
    whois_linked:
      - ""

    # When the player executes `/discord whois <target>` and target is not linked
    whois_not_linked:
      - ""

    # When the player tries to reload the plugin without permission
    no_permission:
      - "&c&l(!) &cNo Permission!"

    # When the player successfully reloads the plugin
    reload:
      - "&e&lDISCORD &8» &aSuccessfully reloaded the plugin."

  discord:
    # When the user successfully links with his/her Minecraft account
    link_success:
      title: "✅ Success!"
      description: "You are now linked with **%player-name%**!"
      thumbnail: "https://minotar.net/avatar/%player-name%"
      color: "00FF00"

    # When the user enters an invalid code
    invalid_code:
      title: "❌ Invalid Code!"
      description: "You entered an invalid code!"
      color: "FF00000"

    # When the user is already linked
    already_linked:
      title: "❌ Already Linked!"
      description: "You are already linked to **%player-name%**! \nType `/discord unlink` in game to unlink with this account."
      color: "FF00000"
