bot_token: ""
guild_id: ""

role_update_period: 30 # In Seconds
code_expiry_time: 60 # In Seconds

database:
  type: "MONGODB"

  # MongoDB Configuration
  mongo:
    connection_string: ""
    database: ""

ranks:
  # Format (See below)
  # Permission: Role ID
  "group.donator": ""

messages:
  minecraft:
    # Default message when the player executes `/discord`
    default:
      - "https://discord.gg/UebcN8zxY5"

    # When the player executes `/discord link` even though the player is already linked
    already_linked:
      - "You are already linked"

    # When the player executes `/discord unlink` even though the player is not linked
    not_linked:
      - "You are not linked"

    # When the player executes `/discord link` and is not already linked
    link:
      - "%code%"

    # When the player executes `/discord unlink` and is currently linked
    unlink:
      - "You unlinked"

    # When the player executes `/discord whois <target>` and target is linked
    whois_linked:
      - ""

    # When the player executes `/discord whois <target>` and target is not linked
    whois_not_linked:
      - ""